// Mock data for demo mode (when Supabase is not configured)

export const DEMO_MODE = !process.env.NEXT_PUBLIC_SUPABASE_URL ||
    process.env.NEXT_PUBLIC_SUPABASE_URL.includes('SEU-PROJETO') ||
    process.env.NEXT_PUBLIC_SUPABASE_URL.includes('your-project-url')

export const MOCK_USER = {
    id: 'demo-user-123',
    email: 'demo@dezapegao.com',
    user_metadata: {
        username: 'usuario_demo',
        phone: '+5511999999999',
    },
}

export const MOCK_PROFILE = {
    id: 'demo-user-123',
    username: 'usuario_demo',
    phone: '+5511999999999',
    plan: 'free' as const,
    ads_count: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
}

export const MOCK_LISTINGS = [
    {
        id: '1',
        user_id: 'demo-user-123',
        title: 'Mesa de madeira maciça',
        description: 'Mesa linda de madeira, semi-nova, comporta 6 pessoas. Perfeita para sala de jantar!',
        price: 450,
        category: 'moveis' as const,
        image_url: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=800&auto=format&fit=crop',
        likes_count: 12,
        whatsapp_clicks: 5,
        status: 'active' as const,
        expires_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date().toISOString(),
        profiles: MOCK_PROFILE,
    },
    {
        id: '2',
        user_id: 'demo-user-123',
        title: 'iPhone 12 Pro 128GB',
        description: 'iPhone em ótimo estado, sem arranhões, bateria 89%. Acompanha capa e carregador.',
        price: 2800,
        category: 'eletronicos' as const,
        image_url: 'https://images.unsplash.com/photo-1592286927505-ed6a5be4e0b6?w=800&auto=format&fit=crop',
        likes_count: 25,
        whatsapp_clicks: 15,
        status: 'active' as const,
        expires_at: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date().toISOString(),
        profiles: {
            id: 'demo-user-456',
            username: 'maria_tech',
            phone: '+5511988887777',
            plan: 'pro' as const,
            ads_count: 8,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
    },
    {
        id: '3',
        user_id: 'demo-user-789',
        title: 'Sofá 3 lugares cinza',
        description: 'Sofá confortável, tecido de qualidade. Usado apenas 1 ano.',
        price: 850,
        category: 'moveis' as const,
        image_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&auto=format&fit=crop',
        likes_count: 8,
        whatsapp_clicks: 3,
        status: 'active' as const,
        expires_at: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date().toISOString(),
        profiles: {
            id: 'demo-user-789',
            username: 'joao_vendedor',
            phone: '+5511977776666',
            plan: 'basic' as const,
            ads_count: 5,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
    },
    {
        id: '4',
        user_id: 'demo-user-101',
        title: 'Bicicleta Caloi aro 29',
        description: 'Bike zerada, freio a disco, câmbio Shimano 21 marchas.',
        price: 1200,
        category: 'esportes' as const,
        image_url: 'https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=800&auto=format&fit=crop',
        likes_count: 18,
        whatsapp_clicks: 9,
        status: 'active' as const,
        expires_at: new Date(Date.now() + 22 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date().toISOString(),
        profiles: {
            id: 'demo-user-101',
            username: 'bike_lover',
            phone: '+5511966665555',
            plan: 'free' as const,
            ads_count: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
    },
    {
        id: '5',
        user_id: 'demo-user-202',
        title: 'PlayStation 4 Slim 1TB',
        description: 'Console perfeito com 2 controles e 5 jogos.',
        price: 1800,
        category: 'eletronicos' as const,
        image_url: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&auto=format&fit=crop',
        likes_count: 32,
        whatsapp_clicks: 16,
        status: 'active' as const,
        expires_at: new Date(Date.now() + 15 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date().toISOString(),
        profiles: {
            id: 'demo-user-202',
            username: 'gamer_pro',
            phone: '+5511955554444',
            plan: 'premium' as const,
            ads_count: 15,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
    },
    {
        id: '6',
        user_id: 'demo-user-303',
        title: 'Tênis Nike Air Max 42',
        description: 'Tênis original, tamanho 42, muito conservado.',
        price: 280,
        category: 'roupas' as const,
        image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop',
        likes_count: 20,
        whatsapp_clicks: 11,
        status: 'active' as const,
        expires_at: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date().toISOString(),
        profiles: {
            id: 'demo-user-303',
            username: 'sneaker_head',
            phone: '+5511944443333',
            plan: 'basic' as const,
            ads_count: 7,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        },
    },
]
